spring.application.name=backend
spring.profiles.active=dev

# Tamaño máximo del archivo individual (ejemplo: 10MB)
spring.servlet.multipart.max-file-size=10MB

# Tamaño máximo total de la solicitud (archivo + otros campos del DTO)
spring.servlet.multipart.max-request-size=10MB